node {
    stage('Preparation') {
        // This pulls the code from the branch i set in Jenkins config
        echo 'Checking out source code...'
        checkout scm
        
        //This is good for the first run to verify the files are there
        sh 'ls -lh'
    }

    stage('Build') {
        // installs project dependencies
        echo 'Installing dependencies now...'
        // Creates the node_modules folder in the root
        sh 'npm install'     
    }
    
     stage('Test') {
        echo 'Running react test ...'
        // run the script file
        sh 'chmod +x jenkins/scripts/test.sh'
        sh './jenkins/scripts/test.sh'
    }
        

}
